### ISSUE TITLE
Crash with Explorer Maps

### ISSUE THREAD

**Issue by palaster** [BlackJar72/ClimaticBiomePlacement#1]
Mod Version Affected: Both 1.1.2 and 1.2.0
MC Version : 1.12.2
Forge Version : 14.23.4.2732
Crash Report (in Game) : https://pastebin.com/C2gSDhrT
Crash Report (in Dev Environment) : https://pastebin.com/j1DxzDnx

Issue: java.lang.ArrayIndexOutOfBoundsException in the biome array at ItemMap.renderBiomePreviewMap.

Steps To Reproduce:
1) Create a new world with Climatic world type
2) Spawn villagers till you find a cartographer.
3) Unlock the cartographer 4 tier trade. The trade after the emeralds for an empty map.
4) Watch as it crashes.

**Comment by BlackJar72** [comment]
OK.  The latest dev version does not crash, but the maps are wildly inaccurate (and basically all the same).  I'll see if I can make the maps correct, then upload a fixed version.

**Comment by BlackJar72** [comment]
The crash should be fixed. Maps are off a a bit (a chunk or so I think), but show basically the correct location.

**Comment by BlackJar72** [comment]
I see there can be a lot of lag; I might try making changes (basically more common Mansion, appearing in any forest type) if I can, but not now.

**Comment by BlackJar72** [comment]
I have a fix for the lag that will be in the next version.

**Comment by BlackJar72** [comment]
The lag from cartographers should be mostly gone now.
