### ISSUE TITLE
Mirrored Generation

### ISSUE THREAD

**Issue by O13SC3N3** [BlackJar72/ClimaticBiomePlacement#10]
https://imgur.com/hiuxrHI
![pregen](https://user-images.githubusercontent.com/11418585/50554572-176be080-0c7a-11e9-9afb-101466fd9a41.png)

After 3 or so worlds pregen and explored widely. i've noticed a common theme here, continents/land mass/islands seem to repeat with very little difference over a given size. Was this intentional? Kinda takes away the new world out of just beating feet a few 1000 chunks.

**Comment by BlackJar72** [comment]
No!  That is definitely not intentional!  And what really confuses me is that it doesn't seem to happen in my own world -- unless I broke something in an update.

**Comment by BlackJar72** [comment]
I can confirm that the climate maps being saved are absolutely identical every time -- I don't know why ... ugghhhh, this is not what I'd planned to do today!

**Comment by BlackJar72** [comment]
I have verified that it is _**generating**_ completely different maps in each region as it should, but for some reason it's _**writing**_ the same map to its save files everywhere.  I have no idea why, I'm stumped and will probably need help from a real Java expert to figure it out.  It's entirely likely this will have to be scrapped as a fail experiment.  :(

EDIT: It's the same files, regardless of seed, which make no sense -- also, I don't see this bug at all in game, but based on what I'm finding must exist!

**Comment by BlackJar72** [comment]
More testing shows this doesn't actually happen in game -- though something _really, **really**_ weird is going on with the save files.  Are you sure this wasn't made with some kind of map pregenerator that interfered?  Or that another mod didn't interfere?

**Comment by O13SC3N3** [comment]
Only Mods are

Biomes O Plenty 7.0.1.2424
Climatic Biomes 2.5.0

I've ran around and explored awhile and noticed the same beach line after a few hours exploring. Decided to dig deeper and had the same continent repeated almost exactly the same. Used a pregen same thing. Made 3 other maps and same thing. Granted the areas are more then large enough and easy to set up a border (4000 Chunks) I just didnt know if this was intentional or not. Its almost like each player could move to a 4000 or so chunk distant away and have their own same area almost.

**Comment by BlackJar72** [comment]
No that shouldn't happen, and what has me confused is why its happen to you.  My world so far is like this:

[![2018-12-31-11-18-53.png](https://i.postimg.cc/1t9fx7Bk/2018-12-31-11-18-53.png)](https://postimg.cc/Y4spY3JR)

Anyway, I'm not sure what's going on -- I can't reproduce this here.

(I was also freaking out over the weirdness with my save files when it turns out my hash utility is broken somehow; the files are all different.)

**Comment by O13SC3N3** [comment]
It seems to repeat after 4000+ Chunks

**Comment by BlackJar72** [comment]
4000 **CHUNKS**?!  It should start a new continent every 4096 blocks.  4000 chunks should be 16 continents, that doesn't look like 16 continents.  I also went ahead and did a quick check -- I used tp to see how things were 1,048,576 blocks (65536 chunks, 256 continents) out.  Nope, I don't get the same maps, even there.  You're not trolling are you?

**Comment by O13SC3N3** [comment]
Not trolling, must be on my end. Ill experiment with it and see what else i come up with.

**Comment by BlackJar72** [comment]
I'll ask if anyone else has seen anything like this.

**Comment by BlackJar72** [comment]
Do you know the exact coords of that map, btw -- so early prototypes had a cycle like that specifically with negative number, but that was fixed.  Maybe certain number ranges and/or seeds are broken?

**Comment by BlackJar72** [comment]
I have found a world that does duplicate but not every continent (one duplicate directly next continent over).  I don't know the period, however, it could be a problem with the math I use to generate random numbers for specific coordinates; it could be this mod has broken seeds.
