### ISSUE TITLE
Pine Slab don't have localized name

### ISSUE THREAD

**Issue by QuantumStatement** [BlackJar72/ClimaticBiomePlacement#11]
Minecraft 1.12.2
Climatic Biome Placement 2.5.0

![2018-12-31_13 24 42](https://user-images.githubusercontent.com/35406698/50558531-3ca33200-0d00-11e9-9bce-f8fed8617fc3.png)

**Comment by BlackJar72** [comment]
Yes, I've been aware of this for some time -- I just don't have any idea why or how to fix it.

**Comment by QuantumStatement** [comment]
Maybe problem lies in this?
https://github.com/BlackJar72/ClimaticBiomePlacement/blob/9a9a883413ea5f6e1b383cf59ca90ea96a8423b2/main/java/jaredbgreat/climaticbiome/blocks/slabs/BlockPineSlab.java#L96-L99

**Comment by BlackJar72** [comment]
Thanks, that did it.  Unfortunately, I have a much more serious problem.  But if there's another update it will be fixed.
