### ISSUE TITLE
TOOOO many pine trees

### ISSUE THREAD

**Issue by KenyMylankca** [BlackJar72/ClimaticBiomePlacement#19]
there are just a lot of pine trees in my world(generated with climatic option) and you say i cant disable them. can't i decrease the amount of their spawn too? it's really boring

**Comment by KenyMylankca** [comment]
edit: i just noticed it's Pine Woods biome. Can i decrease the spawn rate of this biome?

**Comment by KenyMylankca** [comment]
uhm, i removed _**climaticbiomesjbg:pine_swamp**_ from BiomeList.txt file, will it help?

**Comment by BlackJar72** [comment]
That biome is the pine woods, you won't have that anymore, at least not in new continents (that weren't laid out before removing it) -- or, you can go in and delete the climate maps if you don't mind ugly cliffs. 

Now, the sub-tropical forest will still have pines, but less, they basically take the place of birches in vanilla forests there.

**Comment by BlackJar72** [comment]
Ok, you can now turn the pines off or have them made from spruce blocks (as long as you aren't using dynamic trees).

**Comment by KenyMylankca** [comment]
thanks a lot! hope we see this mod on 1.13.2 :)

**Comment by BlackJar72** [comment]
I hope forge will make setting up the modding environment easier by the time they make a release version for 1.13.2.

**Comment by KenyMylankca** [comment]
yeah i hope it too. most of the features currently not implemented, i'm waiting something too

**Comment by CREEATION** [comment]
> or have them made from spruce blocks (as long as you aren't using dynamic trees).

So if I'm using Dynamic Trees this config option will not work?

**Comment by BlackJar72** [comment]
No, this does not affect the dynamic trees compatibility.

**Comment by BlackJar72** [comment]
OK, it will now work with the dynamic trees compatibility if you get the latest version of both.  You will still need to allow modded blocks (at least for now).  Also, consider that the biome where these pines generate are likely not that good for spruce, since these are sub-tropical pines and spruce like cold weather.
