### ISSUE TITLE
Can't get dynamic trees compatibility to work

### ISSUE THREAD

**Issue by BlackJar72** [BlackJar72/ClimaticBiomePlacement#2]
I've done what I can to read the Dynamic Trees API and to figure out how compatibility works -- and ultimately copy a lot of compatibility code.  Unfortunately, while I can get a tree to generate I will neither render with textures nor drop its log.  I have no idea what I'm doing wrong (or just not doing).  I may need help (@the-realest-stu) if I'm to make it work.

**Comment by cadaverous-eris** [comment]
I looked through the blockstates and models folders on the MC1.12.2 branch and I didn't see any blockstates or models for the dynamic leaves or branches. That would probably be why the models aren't working.
Not entirely sure why the drops aren't working. All I can suggest is double checking the registry order to make sure that the tree family's primLog itemstack isn't being created with a null item/itemblock.

**Comment by BlackJar72** [comment]
Thanks, I'll look into fixing those things.  It will make some players very happy.
