### ISSUE TITLE
World Creation SubBiome Spam

### ISSUE THREAD

**Issue by O13SC3N3** [BlackJar72/ClimaticBiomePlacement#20]
Not all Worlds on creation do this, And I've tried to locate what biome 268 is doesn't seem to exist.

Using Climatic Biomes, and Biomes O Plenty

> "[13:58:16] [Server thread/INFO] [STDERR]: [jaredbgreat.climaticbiome.biomes.SubBiomeRegistry:showError:100]: Returning NULL for subbiome id 269
> [13:58:16] [Server thread/INFO] [STDERR]: [jaredbgreat.climaticbiome.biomes.SubBiomeRegistry:showError:101]: Subbiome 269 must be registeerd!
> [13:58:16] [Server thread/INFO] [STDERR]: [jaredbgreat.climaticbiome.biomes.SubBiomeRegistry:showError:102]: *******************************************
> [13:58:16] [Server thread/INFO] [STDERR]: [jaredbgreat.climaticbiome.biomes.SubBiomeRegistry:showError:99]: *******************************************
> MultiMC stopped watching the game log because the log length surpassed 100000 lines.
> You may have to fix your mods because the game is still logging to files and likely wasting harddrive space at an alarming rate!"
>

**Comment by BlackJar72** [comment]
It looks like "minecraft:ice_mountains:1" is being used somewhere but has not been created in the biome variants.

**Comment by O13SC3N3** [comment]
when you exit and reload the world the issue seems to go away, So not sure if its a big issue, but game does slow down until you do save and exit.

**Comment by BlackJar72** [comment]
Did you change a file?  This will happen every time a chunk is being generated with an unfamiliar ID (and should persist until either the variant is created or the climate map is deleted to be remade).  Before adding this the same error simply crashed the game.  Alternately, if the whole biome generated before you shut the game down that also would have fixed it.

Taking the message out would stop the "spam," but would also mean errors would often persist without being found or fixed.  Affected areas would just generate as ocean now, due to a failsafe.  Actually, I should really find a way to send it to chat so the game can be should down immediately.

If there was no error that's a more serious problem, since it means a config or save is not being read correctly.

**Comment by O13SC3N3** [comment]
No, I have not changed anything within Climatic Biomes, or Biomes O Plenty. 

I do however have mods like Minecraft Boom, Pandora's Box, Recurrent Complex, and Ruins that like to cause cascading world gen on world creation. The sub biome id spam doesn't happen all the time, maybe 40-50% of the time creating a world.

**Comment by BlackJar72** [comment]
It sounds like there is a bug in a config, if you've altered them, where an ice_mountains variant is used and not configured correctly.  When this doesn't happen its likely that biome simply wasn't present.  If this occurs when creating a new world its likely that when you restart the chunks already exist so its no longer hitting the error.

I suppose I could add a fail-fast option to just crash when hitting this, but probably not tonight.

**Comment by O13SC3N3** [comment]
Ill delete the configs and let them regenerate and see if it still appears

**Comment by O13SC3N3** [comment]
Still get the error every once in awhile creating worlds. Even with other mods like Project Vibrant Journeys (Biomes On/Off) and so on.

**Comment by BlackJar72** [comment]
Same numbers?  Then it looks like it's not loading its own biome variants correctly -- it has:
`minecraft:ice_mountains:1 1.5, 0.5`
and in AlpineCold.cfg
`noise(minecraft:ice_mountains, 5, minecraft:ice_mountains:1)`
But for some reason it's not reading it correctly -- 269 can only be ice_mountains:1 (13 + 256).  I'll have to look and see.

**Comment by O13SC3N3** [comment]
Well its still 50/50 seems like Biome 168 threw the next one. Seed: 8325346719895606960 doesn't throw it at all so far. Im going through my modpack to see if it could be another culprit as well.

**Comment by BlackJar72** [comment]
That's strange -- biome 168 is "Bamboo Jungle‌" as of Minecraft 1.14 -- it's not an extended biome (those start at 256), and not a vanilla biome in 1.12.  It must be a biome from (I assume another) mod.

One other thing that can cause this: If a biome was removed (such as by un-installing a mod) in an existing world this will also happen.  Continents are pre-generated to map everything out and the map is stored with game save data, so fixes.

Is this a new world or an old one?

**Comment by O13SC3N3** [comment]
New, Ill let you know what I find out as I go through everything. Biome 268 did throw with just the two mods installed BoP and Climatic, so idk if it has anything to do with BOP

**Comment by BlackJar72** [comment]
OK, 268 is different -- Snowy Tundra / ice_plains -- a vanilla variant.  I don't think there should be any variants on that, but I'll check once I get home.

(Before you actually typed 168.)

**Comment by O13SC3N3** [comment]
Randomly doing fresh installs, config changes, piece by piece to address a few other issues ive gotten. Earlier errors for biomes 263 and 267 thrown.

Then in the console on a reboot

[13:12:56] [main/INFO] [STDERR]: [jaredbgreat.climaticbiome.biomes.SubBiomeRegistry:add:53]: Adding Biome with id 263
[13:12:56] [main/INFO] [STDERR]: [jaredbgreat.climaticbiome.biomes.SubBiomeRegistry:add:53]: Adding Biome with id 267

And created a world with same seed no issues came up with 263 and 267...

Only Mods added so far is:

  autothirdperson-1.2.0
  BiomesOPlenty-1.12.2-7.0.1.2425-universal
  ClientTweaks_1.12.2-3.1.11
  ClimaticBiomes-2.6.3-MC1.12.2
  DynamicSurroundings-1.12.2-3.5.4.3
  DynamicSurroundingsHuds-1.12.2-3.5.4.0BETA
  DynamicTrees-1.12.2-0.9.4
  DynamicTreesBOP-1.12.2-1.4.1e
  DynamicTreesCB-1.1.0-MC1.12.2
  foamfix-0.10.3-1.12.2
  OreLib-1.12.2-3.5.2.2
  ProjectVibrantJourneys-1.12.2-1.6.0
  randomconfigs-1.12.2-1.3.2.3
  randompatches-1.12.2-1.13.0.1
  randomtweaks-1.12.2-2.4.3.1
  SoundFilters-0.10_for_1.12
  VanillaFix-1.0.10-99
  VanillaTweaks-1.4.7

**Comment by BlackJar72** [comment]
Maybe I should change that to not use [STDERR], since those are not actually errors -- originally it was set up to use the error stream since it automatically flushes after each output (so better to debug timing). 

Those biomes are actually supposed to be added and can't be removed -- those are the hard-coded deep river and deep frozen river variations that help rivers stay navigable.

**Comment by O13SC3N3** [comment]
Just thought it was interesting that console log wasnt in the first time I loaded Climatic and BoP, errors in console for each spamming console. When I exited and rebooted the modpack because I wanted to check maybe I did something wrong. That was in the console. So I made the same world seed and the issues didnt spam the console like before.

So it made me think that maybe one of the mods I had wasnt allowing Climatic enough time? idk

**Comment by WenXin20** [comment]
How was this solved? I'm having the same issue happening to me upon world creation. The world refuses to load and just hangs. The biome ids being thrown are 276, 292, and 274. This didn't happen before I added any biomes, so I'm currently removing half of these at a time until I can find what might be causing it. 
The plains config file in the custom folder is the only file that I have edited:
`biome("floricraft:rose land")`
`biome("floricraft:tulip land")`
`biome("tolkienmobs:gladden fields")`
`biome("tolkienmobs:the brown lands")`
`biome("tolkienmobs:tyrn gorthad")`
`biome(byg:balliumfields)`
`biome(byg:bmeadow)`
`biome(byg:bpraire)`
`biome(byg:bstellatapasture)`
`biome(candymod:biome_cotton_candy)`
`biome(candymod:biome_gummy_swamp)`
`biome(defiledlands:plains_defiled)`
`biome(erebus:elysian_fields)`

**Comment by BlackJar72** [comment]
OK, that is confusing -- those numbers correspond to user variants of the vanilla biomes Forest Hills, Extreme Hills Edge, and Savanna Plateau.  I'm not sure why you're getting those.  It shouldn't have anything to do with those mods.  All those biomes should have id's less than 256, unless the authors did something weird (like what this mod and OTG do creating "fake" id's).  I'm not sure what's going on, if you have no biomes with a "...:1" at the end.  You could try deleting everything in the ./config/ClimaticBiomes/BiomeConfig folder and re-running.  If that doesn't work could you find a way to send me a zip file of the whole config/ClimaticBiomes folder?

Before you do that though, you might want to try re-running and reloading the world, then creating a new one.  I just deleted the data fold in my dev environment and ran the game -- it was really lagging and crashed the first time but was fine afterwards.  I'm not sure what caused it, but it didn't do this before this does bother me now.

**Comment by WenXin20** [comment]
Deleting everything and rerunning was the first thing I had tried and it worked fine when creating a world. It was after adding those modded biomes back that I saw the problem again.
One of the mods I have is Biomes You'll Go (id is byg), which is a MCreator mod. Could that affect it?

**Comment by BlackJar72** [comment]
I wouldn't think so.  I never did like those mod-maker apps since they make messy code and don't usually support config file (not that they'd work with the kind of mods I make anyway).  But I don't think it would create mods with strange IDs.

I may have to look at how its loading things to be sure there are no bugs.  I will say that once an invalid ID is in a world it will stay there -- the continent / climate zones are saved so it won't have to re-create them.  I don't know how they would have gotten there though if the world wasn't created using them.

**Comment by WenXin20** [comment]
I have been creating a new world every time to test for that error.

**Comment by WenXin20** [comment]
I tried it on a pack with only the mods installed that was in the plains config, and it seemed to work fine.
So I added all the mods that had biomes added to the test pack, which gave me the error again, but with ids 315 and 323 instead.

**Comment by BlackJar72** [comment]
It definitely sounds like something else is interfering or is corrupting some data.  Its probably beyond me to figure it out -- it would be hard to tell what mod is even causing it, no telling what it's doing (nothing "normal" to be sure) or how it leads to this. Very likely, but I not at all certainly, a core mod.  It is clearly something that does something exotic with world-gen, not just adding a biome.  It looks like somehow something it stomping on this mods memory or trying to insert other numbers into world-gen in some strange way.  Or, maybe defining its own extended biome id's and returning those when asked -- but this mod looks them up with its own system too.  Either way I probably can't do anything about it.

**Comment by WenXin20** [comment]
I just teleported to the Gladden Fields from Tolkien Mobs mod using the Nature's Compass and the log spam happened again, which gave me 274, 315, and 323. It caused the chunks to post very slowly.

If nothing can be done, that's alright, although disappointing. Thanks for the help though!

**Comment by WenXin20** [comment]
Would a modlist help any?

**Comment by BlackJar72** [comment]
Maybe ... probably not ... but its possible....

**Comment by WenXin20** [comment]
Here's a list:
Aether II
Advent of Ascension
Aroma1997's Dimensional World
Aroma1997 Core
Auxiliary Biomes
Biomes O' Plenty
Oh the Biomes You'll Go
Better Fps
Better Nether
Candy World
Climatic Biomes
Code Chicken Lib
Defiled Lands
Dumpster Diving
Dust
Dynamic Trees
Dynamic Trees BOP
Dynamic Trees Climatic Biomes
Erebus
Floricraft
Foam Fix
Just Enough IDs (This mod adds more biome ids)
Land craft
Land core
Maiden's Marvelous Materials
Mario 2
Raycore
Mubble
Nether Ex
No Cubes
RenderChunk-RebuildChunk
Optifine
Plants 2
Placebo
Project: Vibrant Journeys
Random Things
Redstone Flux
Redwoods
Rockhounding Surface
Rockhounding Core 
The Space Age
Simply Tea
Spooky Biomes
Proxy's Lib
Sugiforest
Tiny Mob Farm
TenshiLib
Tolkien Mobs
Tolkien Tweaks
Brandon's Core
Twilight Forest
Valiux
Vanilla Fix
World's Retold

Hope this helps!

**Comment by BlackJar72** [comment]
That's a long list, and I can't go through all of them.  The Just Enough IDs was suspicious, but simply adding that to my current (very small) pack didn't cause any problems and may have even sped things up a bit.

One thing that might happen, though, is that Just Enough IDs might work as long as less than 256 biomes exist, but become a problem when more than 256 biomes exist (and it starts grabbing bigger IDs).  Having more than the vanilla 256 real biomes will be a problem with this mod.  I'm not sure why these IDs would be in your map, though, unless it actually moves IDs around (or some other mod is also doing something, like converting / inserting some biomes).  

One thing you could do is to create a reduced pack for use with this mod, where all the biome adding mods you aren't actually using in the world are removed (and dimension mods are kept to a minimum, they add biomes too after all -- or even remove them all temporarily for testing).  That might solve the problem, and even if not it would whether that is the case or not.

**Comment by BlackJar72** [comment]
If that doesn't help there may be nothing I can do -- I don't have time to go through all those mods to find out which one is the problem.  Even if I did I probably would not be able to do anything about it anyway.  

I can tell you, though, that Aether II and Twilight Forest are not problems (at least not on their own / besides contributing to the number of biomes).

If reducing the number of biomes doesn't help (or you just can't stand to do it) then sorry, this may just not work with that pack.

**Comment by WenXin20** [comment]
Alright, thanks, I'll try to see what I can find out.

**Comment by BlackJar72** [comment]
OK.  Even if I can't help further, would you kindly share where results you get.  It might be useful in the long run.

**Comment by WenXin20** [comment]
Sure!
