### ISSUE TITLE
World crash when minecraft biomes are disable.

### ISSUE THREAD

**Issue by CapturedCherry-zz** [BlackJar72/ClimaticBiomePlacement#21]
When I disable minecraft biomes in the mod config the world will crash on world gen. I tested
 this with both Traverse and Biome of plenty. Both of them crashed at the same point with the same crash log.

Crash log
https://pastebin.com/bipZJHyH

**Comment by BlackJar72** [comment]
I'll have to look at that -- the first thing that comes to mind it there may be a biome type that lacks biomes -- which would crash.  If it has no biome to select for a type it will crash (thus the warning in the config itself).  This results in division by zero when it tries to select from 0 of 0 biomes.

Remember, if you turn off vanilla biomes you are actually get rid of all of them (including oceans, rivers, and beaches, and other technical or easy to forget biomes), plus the default use of biomes from this mod.

One problem does come to mind also -- I'm not sure if I have a way to substitute in new beaches.

**Comment by BlackJar72** [comment]
Actually, I should probably remover that option -- and if you don't want them just clear out the files that add them.

**Comment by CapturedCherry-zz** [comment]
Ok thanks. I have try so many ways to remove most of minecrafts biomes so I could use a different mod instead. There are mods that let you replace the minecraft biomes with one biome but its only one biome so that's no uses.

**Comment by BlackJar72** [comment]
The way you'd do that with this is to edit the files in _config/ClimaticBiomes/BiomeConfig/Minecraft_, replacing the vanilla resource locations with the modded ones.

The thing you have to be careful about is simply this: Unless it's already empty for vanilla anyway, you must have at least one biome available.  Empty lists crash.

**Comment by BlackJar72** [comment]
The last couple versions, uploaded today, should be a bit more robust/resilient -- though empty biome lists will be refilled with vanilla biomes as a failsafe, so off vanilla biomes without making sure all lists have at least one biome may not always get the results you expect.
