### ISSUE TITLE
I seem top be getting a crash 

### ISSUE THREAD

**Issue by Quinnplaysgamestv** [BlackJar72/ClimaticBiomePlacement#24]
I seem to be getting a strange crash here is the link to it.

https://paste.dimdev.org/ixatomaqas.mccrash

**Comment by BlackJar72** [comment]
It's trying to generate a river beyond the bounds the map; it shouldn't do that.  I'll try to figure out how this is happening and fix it over the weekend.

**Comment by BlackJar72** [comment]
Nevermind, I think I fixed it.  It was a small problem of some other checks being done on rivers before checking bounds (which should have been done first).

**EDIT:** I just uploaded a new file that should have the fix, just waiting for it to be OK'ed by Curse.
