### ISSUE TITLE
Can't Find Any Village

### ISSUE THREAD

**Issue by KenyMylankca** [BlackJar72/ClimaticBiomePlacement#26]
i can't find any village, in [my modpack](https://github.com/KenyMylankca/Harshen-Modpack). i choosed climatic option on world generation, but couldn't face with any village so far. please help me
edit: Forge: 2836 (1.12.2)

**Comment by BlackJar72** [comment]
I'll take a look at your modpack and see if I can find any problems.  I don't have this problem, though what I'm using is a small number of mods that are mostly vanilla+ kind of stuff.

**Comment by KenyMylankca** [comment]
i just found one, sorry for my foolish. but it was bit hard :D

**Comment by BlackJar72** [comment]
Cool, saves me looking -- now I can get back to other fixes / upgrades (maybe one day I'll have the time to give this the same love Doomlike Dungeons got when it was young?).
