### ISSUE TITLE
Got this crash loading into a world. 

### ISSUE THREAD

**Issue by Winddbourne** [BlackJar72/ClimaticBiomePlacement#30]
I'm not sure exactly what caused the crash but since I used a program that posts the report online for me I'm sharing the link to you here. 

https://paste.dimdev.org/tajobuhesu.mccrash

**Comment by BlackJar72** [comment]
Try the new one in a few minutes once it's been approved.

**Comment by Winddbourne** [comment]
I can't say if this fixed it or not . . . the crash happened on trying to create a new world and normally I don't have issues with the mod. . . but I am very impressed at how fast you looked at this crash report and got out a fix! You are appreciated. :)

**Comment by BlackJar72** [comment]
It should be mostly fixed (though in a slightly hacky way).  It occurs to me now that a couple of tiny areas in (2x2 chunks each) could still have the problem.  But unless I get more crash reports in I may not be so fast in those fixes.
