### ISSUE TITLE
Heavily expand supported modded biomes

### ISSUE THREAD

**Issue by Sunconure11** [BlackJar72/ClimaticBiomePlacement#31]
Here's a list of some biome-adding mods I am aware of, or mods that have a few biomes, at least.

> Vampirism
> Novam Terram
> Auxiliary Biomes
> Redwoods
> Sugi Forest
> Abyssalcraft
> Thaumcraft
> Ice and Fire
> Zoesteria
> Project Vibrant Journeys

**Comment by BlackJar72** [comment]
I'll look into it ... and maybe have it protect itself from biomes that have been disabled in another mods config while I'm at it (like, if a biome is null, just don't add it to the list).

**Comment by Sunconure11** [comment]
I also forgot about Environs++

**Comment by BlackJar72** [comment]
I have Terram Novam support in the source repo now -- I may way to release it until I have more of these other mods included ... depending on how long I think I'll take.

**Comment by BlackJar72** [comment]
I may also treat special biomes from non-biome mods differently than I treat biome mods per se.

**Comment by BlackJar72** [comment]
I have basically done this, but, **_I will not be supporting Zoestria_** until its author stops putting white spaces in resource locations.  Sorry, just to much trouble to fool with.
