### ISSUE TITLE
More Modded Biomes Support

### ISSUE THREAD

**Issue by WenXin20** [BlackJar72/ClimaticBiomePlacement#32]
Here are some mods I have that also have biomes added. Could default support be added?
- [Biomes You'll Go](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go) - 65 Biomes
- [Candy World](https://www.curseforge.com/minecraft/mc-mods/candy-world) - 3 Biomes
- [Defiled Lands](https://www.curseforge.com/minecraft/mc-mods/defiled-lands) - 7 Biomes
- [Explorercraft](https://www.curseforge.com/minecraft/mc-mods/explorercraft-worldexpansion) - 3 Biomes
- [Mario 2](https://www.curseforge.com/minecraft/mc-mods/mario-mod-2) - 4 Biomes
- [Mubble](https://www.curseforge.com/minecraft/mc-mods/mubble) - 1 Biome
- [Redwoods](https://www.curseforge.com/minecraft/mc-mods/redwoods) - 5 Biomes
- [Rockhounding Surface](https://www.curseforge.com/minecraft/mc-mods/rockhounding-mod-surface) - 1 Biome
- [Spooky Biomes](https://www.curseforge.com/minecraft/mc-mods/spooky-biomes) - 2 Biomes
- [Tolkien Mobs](https://www.curseforge.com/minecraft/mc-mods/tolkien-tweaks-mobs-edition) - 14 Biomes
- [Valiux](https://www.curseforge.com/minecraft/mc-mods/valiux-reborn-adventure-ores) - 1 Biome
- [Wild Nature](https://www.curseforge.com/minecraft/mc-mods/wildnature) - 77 Biomes

**Comment by BlackJar72** [comment]
It supports Mubble now.  Some wild nature biomes don't generate right unless you use the Wild Nature world type (or maybe they're just still not working in general?).

I'll look into some of these others for a possible future update.

**Comment by WenXin20** [comment]
Ok, thanks!

**Comment by BlackJar72** [comment]
Also, Tolkien mods has the same problem that kept Zoestria from being supported it uses white spaces in its resource locations.  (This is **BAD**!)  So, it probably won't be supported.

**Comment by BlackJar72** [comment]
Done.

**Comment by Sunconure11** [comment]
Would it be possible to add support for the mod Future MC? Mainly asking since it ports the bamboo forest from newer versions of MC to 1.12.2.

**Comment by BlackJar72** [comment]
I could.  Maybe not today, but I'll look into it.
