### ISSUE TITLE
Support for Grit Mod

### ISSUE THREAD

**Issue by WenXin20** [BlackJar72/ClimaticBiomePlacement#37]
The new mod, [Grit](https://www.curseforge.com/minecraft/mc-mods/grit), adds in a Tropical Desert Biome.

**Comment by BlackJar72** [comment]
I'll look into adding that to the special biomes (i.e., biome from non-biome mods).

**Comment by BlackJar72** [comment]
Grit support has been added to the development version and will be available in version 2.14.
