### ISSUE TITLE
Update for Biomes You'll Go

### ISSUE THREAD

**Issue by WenXin20** [BlackJar72/ClimaticBiomePlacement#39]
[Biomes You'll Go](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/2766605)  v1.6.8 Beta 1, 2, & 3 added new biomes for 1.12.2.

- 'Tropical Islands' [Warm]
- 'Cypress Swamplands' [Warm]
- 'Outlands' [Desert]
- 'Red Outlands' [Desert]
- 'Amaranth Fields'
- 'Giant Blue Spruce Taiga' 
- 'Giant Seasonal Spruce Taiga'
- 'Dover Mountains' [Cold]

**Comment by BlackJar72** [comment]
Done

**Comment by WenXin20** [comment]
This mod updated to a release version, v1.6.8, with at least 3 new biomes:
- Pine Lowlands
- Stone Brushlands
- Bluff Mountains

**Comment by BlackJar72** [comment]
Next week ... I've updated this enough for one day.
