### ISSUE TITLE
Disabled BoP Biomes cause a crash

### ISSUE THREAD

**Issue by ghost** [BlackJar72/ClimaticBiomePlacement#4]
I have some BoP biomes disabled using BoP's biome config and when trying to use this mod it will crash the game. I notice you have the default traverse config linked on your mod page, any chance you could make a BoP version also so we can disable biomes as needed. A related request would be to just include them in the mod files under a preset folder so the additional download isn't required, it would increase the mod's size only trivially and would really help out and also security wise not require downloading from a 3rd party

**Comment by BlackJar72** [comment]
Perhaps, I'll see what I can do, but it probably won't be tonight.

Hmmm... preset folders -- I hadn't thought of that; that might be a good idea.

**Comment by BlackJar72** [comment]
Here, a preview:
[https://www.mediafire.com/file/kxubsu7hfwddch7/BiomeList-BoP.zip/file](https://www.mediafire.com/file/kxubsu7hfwddch7/BiomeList-BoP.zip/file)

It won't completely work until the next update (cool forests / plains / parks only show up if BoP is enabled, so I'll add an option to turn it on manually).

I'll make this publically available once I've added the config option.

**Comment by BlackJar72** [comment]
I may also try to make the built-in support more tolerant of such things.

**Comment by BlackJar72** [comment]
Download the new update and the BoP file and you should be ready to edit.

**Comment by ghost** [comment]
Absolutely fantastic work. Thanks a lot

**Comment by BlackJar72** [comment]
You're welcome -- and I may try that prefab idea in a future update.
