### ISSUE TITLE
World Is So Weird (1.12.2)

### ISSUE THREAD

**Issue by KenyMylankca** [BlackJar72/ClimaticBiomePlacement#40]
I just created a new world using the latest version on curse(beta) in [my modpack](https://github.com/KenyMylankca/Kenijeys-Modpack). And the settings i did is selecting biome size to 32 and enable extra beaches. and it crashes with Dynamic Trees Climatic Biomes compat but it's another issue :D
![2019-08-23_09 12 31](https://user-images.githubusercontent.com/41585837/63570532-41b23b80-c586-11e9-9be9-9b0efce65dee.png)

**Comment by BlackJar72** [comment]
Here, try this with that modpack and seed and see what happens:
http://www.mediafire.com/file/y1gap95a9sdi4o8/ClimaticBiomes-2.14.1b-MC1.12.2.jar/file

(If that doesn't fix it I have no clue what the problem could be.)

**Comment by KenyMylankca** [comment]
sure

**Comment by BlackJar72** [comment]
Thanks.  I hope it works.

**Comment by KenyMylankca** [comment]
ahh i forgot to say, i also choosed map scale x2. and now i'm re-generating the same world.
![aaa](https://user-images.githubusercontent.com/41585837/63597366-f586eb80-c5c5-11e9-9d94-8f300d1b9e0e.PNG)
![sss](https://user-images.githubusercontent.com/41585837/63597396-0899bb80-c5c6-11e9-8a9f-7818ed012f61.PNG)

**Comment by KenyMylankca** [comment]
uhm no, kinda same... :(
![2019-08-23_16 52 46](https://user-images.githubusercontent.com/41585837/63597595-8067e600-c5c6-11e9-8813-b34568c0f27a.png)

**Comment by BlackJar72** [comment]
Is it like that everywhere?  Or is this a rare "freak" occurrence?

I have no idea what could cause something like that.  The only difference to the generation system between 2.14 and 2.13 is that some variable that were read from a class called ConfigHandler are now read from a class called ClimaticWorldSettings.  But the biome provider should get the same data and work the same -- it doesn't even have its own chunk generator!

(EDIT: My worlds look the same.)

**Comment by BlackJar72** [comment]
Testing in 2.13.8 (without the full pack):

https://i.postimg.cc/HLPRDDM7/2019-08-23-10-29-37.png

Even using that seed in vanilla gives some pretty wild clifts very close to there (that exact spot become plains, but there is hilly biome next to it with lots of crazy clifts and arches).

Unless it's all over that place it may just be crazy world-gen from the vanilla chunk generator, enhanced by taller than vanilla modded biomes.

**Comment by KenyMylankca** [comment]
lol so i don't know what to do, i can post more comments about more weird worlds in future if u wish... but this wasn't happening beforetime.

**Comment by BlackJar72** [comment]
If you want to ... I may try taking a look with the actual mod pack.  It's very strange because with this mod by itself the changes don't seem to affect terrain at all.

**Comment by KenyMylankca** [comment]
dunno, maybe BOP or something else..

**Comment by KenyMylankca** [comment]
hey uhm i made new tests with the fixed version of dynamic trees compat of climatic biomes, but didn't select map scale, it works fine. i mean i can't see anything weird in the world. i just choosed biome size to 32 and it's actually how i want the biomes... i think u can close this issue if u wish.
