### ISSUE TITLE
v2.14.6 crashes with many mods installed, while v2.14.5 doesn't.

### ISSUE THREAD

**Issue by Thombias** [BlackJar72/ClimaticBiomePlacement#44]
Hopefully this crash-report is helpful enough. I guess the new version screwed something up that was working just fine with the previous version with all the mods i have installed.
I also tested it with all 3 config options regarding mod blocks set to true and it still crashes.
Anyway, here is the crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ToolProgressionPlugin (toolprogression-core-1.12.2-1.6.6.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.19.2-release.jar)
  Quark Plugin (Quark-r1.6-177.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  F5FixLoadingPlugin (f5fix-1.2.jar)
  CharmLoadingPlugin (Charm-1.12.2-1.3.6.jar)
  No More Glowing Pots (nomoreglowingpots-1.2.jar)
  LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 9/29/19 11:39 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Climatic Biomes (climaticbiomesjbg)
Caused by: java.lang.ExceptionInInitializerError
	at jaredbgreat.climaticbiome.ClimaticBiomes.init(ClimaticBiomes.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at jaredbgreat.climaticbiome.biomes.basic.ActiveVolcano.<clinit>(ActiveVolcano.java:20)
	... 41 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3108555632 bytes (2964 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -Xms4G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_E3 69 mods loaded, 69 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version                     | Source                                       | Signature                                |
	|:----- |:--------------------- |:--------------------------- |:-------------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft             | 1.12.2                      | minecraft.jar                                | None                                     |
	| LCHI  | mcp                   | 9.42                        | minecraft.jar                                | None                                     |
	| LCHI  | FML                   | 8.0.99.99                   | forge-1.12.2-14.23.5.2847.jar                | None                                     |
	| LCHI  | forge                 | 14.23.5.2847                | forge-1.12.2-14.23.5.2847.jar                | None                                     |
	| LCHI  | jei                   | 4.15.0.268                  | jei_1.12.2-4.15.0.268.jar                    | None                                     |
	| LCHI  | quark                 | r1.6-177                    | Quark-r1.6-177.jar                           | None                                     |
	| LCHI  | autoreglib            | 1.3-32                      | AutoRegLib-1.3-32.jar                        | None                                     |
	| LCHI  | baubles               | 1.5.2                       | Baubles-1.12-1.5.2.jar                       | None                                     |
	| LCHI  | baubleshulkerboxes    | 4r                          | BaubleShulkerBoxes-1.12.2-4r.jar             | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHI  | bettershears          | 1.12.2-2019_1.3r-LANGUPDATE | bettershears-1.12.2-2019_1.3r-LANGUPDATE.jar | None                                     |
	| LCHI  | bottledmilk           | 1.0.0                       | BottledMilk-1.12-1.1.0.jar                   | None                                     |
	| LCHI  | charm                 | 1.12.2-1.3.6                | Charm-1.12.2-1.3.6.jar                       | None                                     |
	| LCHI  | chunkanimator         | 1.2                         | ChunkAnimator-MC1.12-1.2.jar                 | None                                     |
	| LCHI  | cleanview             | 1.12.2-v1c                  | CleanView-1.12.2-v1c.jar                     | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCHE  | climaticbiomesjbg     | 2.14.6                      | ClimaticBiomes-2.14.6-MC1.12.2.jar           | None                                     |
	| LCH   | combatrefined         | 1.4.1                       | combatrefined-1.4.2.jar                      | None                                     |
	| LCH   | comforts              | 1.4.1.2                     | comforts-1.12.2-1.4.1.2.jar                  | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCH   | cosmeticarmorreworked | 1.12.2-v4a                  | CosmeticArmorReworked-1.12.2-v4a.jar         | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCH   | wearablebackpacks     | 3.1.3                       | WearableBackpacks-1.12.2-3.1.3.jar           | None                                     |
	| LCH   | corpsecomplex         | 1.0.6                       | corpsecomplex-1.12.2-1.0.6.jar               | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCH   | cosmeticbeds          | 1.12.2-1.0.2.2              | cosmeticbeds-1.12.2-1.0.2.2.jar              | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCH   | crowmap               | 1.1.2                       | crowmap-1.1.2.jar                            | None                                     |
	| LCH   | disenchanter          | 1.6                         | disenchanter-[1.12]1.6.jar                   | None                                     |
	| LCH   | dldungeonsjbg         | 1.12.10                     | DoomlikeDungeons-1.12.10-MC1.12.2.jar        | None                                     |
	| LCH   | enchdesc              | 1.1.15                      | EnchantmentDescriptions-1.12.2-1.1.15.jar    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | exactspawn            | 1.12-1.2.3.17               | ExactSpawn-1.12-1.2.3.17.jar                 | None                                     |
	| LCH   | felling               | 1.4.1                       | felling-1.4.1-1.12.x.jar                     | None                                     |
	| LCH   | fertilization         | 1.0.7                       | Fertilization_1.12.2-1.0.7.jar               | None                                     |
	| LCH   | forgelin              | 1.8.4                       | Forgelin-1.8.4.jar                           | None                                     |
	| LCH   | librarianlib          | 4.19.2                      | librarianlib-1.12.2-4.19.2-release.jar       | None                                     |
	| LCH   | hooked                | %VERSION%                   | hooked-1.0.3.jar                             | None                                     |
	| LCH   | horsetweaks           | 1.0.5                       | HorseTweaks_1.12.2-1.0.5.jar                 | None                                     |
	| LCH   | inventoryspam         | 1.0.5                       | InventorySpam-1.12.2-1.0.5.jar               | None                                     |
	| LCH   | ironfurnaces          | 1.3.5                       | ironfurnaces-1.3.5.jar                       | None                                     |
	| LCH   | jmh                   | 2.1                         | jmh_1.12-2.1.jar                             | None                                     |
	| LCH   | materialchanger       | 1.0                         | materialchanger1.0.3-1.12.2.jar              | None                                     |
	| LCH   | mendingfix            | 1.0.1-1.12.2.2618           | mendingfix-1.0.1-1.12.2.2618.jar             | None                                     |
	| LCH   | nethergoldore         | 1.2.1                       | nethergoldore-1.2.1-mc1.12.x.jar             | None                                     |
	| LCH   | netherportalfix       | 5.3.17                      | NetherPortalFix_1.12.1-5.3.17.jar            | None                                     |
	| LCH   | nomoreglowingpots     | 1.2                         | nomoreglowingpots-1.2.jar                    | b851b8b7c7f4d8d0e910ff27618150ba80c026ec |
	| LCH   | terracore             | 2.1.13                      | TerraCore-1.12-2.1.13.jar                    | None                                     |
	| LCH   | ore_controller        | 1.12-1.0.12                 | OreController-1.12-1.0.12.jar                | None                                     |
	| LCH   | pitweaks              | 1.12-1.1.1                  | PiTweaks-1.12-1.1.1.jar                      | None                                     |
	| LCH   | potioncore            | 1.8_for_1.12.2              | PotionCore-1.8_for_1.12.2.jar                | None                                     |
	| LCH   | potionfixer           | 1.0.0                       | potionfixer-v1.0.0-mc1.12.2.jar              | None                                     |
	| LCH   | qualitytools          | 1.0.7_for_1.12.2            | QualityTools-1.0.7_for_1.12.2.jar            | None                                     |
	| LCH   | roguelike             | 1.8.0                       | RoguelikeDungeons-1.12.2-1.8.0.jar           | None                                     |
	| LCH   | roughmobs             | 2.0.0                       | roughmobs2-1.12.2_2.0.15.jar                 | None                                     |
	| LCH   | simplecore            | 1.7.3.4                     | simplecore-1.12.2-1.7.3.4.jar                | None                                     |
	| LCH   | simpleores            | 1.11.2.2                    | simpleores-1.12.2-1.11.2.2.jar               | None                                     |
	| LCH   | simplesponge          | 3.6.2                       | SimpleSponge-1.12.2-3.6.2.jar                | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| LCH   | sipl                  | 1.6                         | Simply+Platinum+MC+1.12.2+(1.6).jar          | None                                     |
	| LCH   | smoothbedrock         | 1.12.2-3.0.0.122            | SmoothBedrock-1.12.2-3.0.0.122.jar           | None                                     |
	| LCH   | sparkshammers         | @VERSION@                   | sparkshammers-1.12.2-1.9.2.jar               | None                                     |
	| LCH   | stats_keeper          | 3.1.13                      | StatsKeeper-1.12.2-3.1.13.jar                | None                                     |
	| LCH   | swisscheese           | 1.1                         | SwissCheese-1.1-1.12.jar                     | None                                     |
	| LCH   | torohealthmod         | 1.12.2-11                   | torohealth-1.12.2-11.jar                     | None                                     |
	| LCH   | toughnessbar          | 2.1                         | toughnessbar-2.3.jar                         | None                                     |
	| LCH   | tramplestopper        | 1.2.0.4                     | tramplestopper-1.12.2-1.2.0.5-universal.jar  | None                                     |
	| LCH   | teleporter            | ${version}                  | VanillaTeleporter-1.12.2-1.7.1.jar           | None                                     |
	| LCH   | veining               | 1.3.2                       | veining-1.3.2-1.12.x.jar                     | None                                     |
	| LCH   | weirdinggadget        | 1.0                         | weirdinggadget-1.12.2-2.1.16-universal.jar   | None                                     |
	| LCH   | wolfarmor             | 2.2.3.6                     | wolfarmor-1.12.2-2.2.3.1798-universal.jar    | None                                     |
	| LCH   | xpfromharvest         | 1.1.0                       | xpfromharvest-1.12.2-1.1.0.jar               | None                                     |
	| LCH   | deathmaps             | 1.0.0                       | deathmaps-1.12.2-1.0.0.jar                   | 7b14aaee2dd17b12a140baecab28948fff3a263f |
	| LCH   | toolprogression       | 1.12.2-1.6.6                | toolprogression-1.12.2-1.6.6.jar             | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| LCH   | totemexpansion        | 1.2.2                       | totemexpansion-1.2.2-1.12.2.jar              | None                                     |
	| LCH   | vt                    | 1.12.2-1.5.5                | VanillaTweaks-1.12.2-1.5.5.jar               | None                                     |
	| LCH   | librarianliblate      | 4.19.2                      | librarianlib-1.12.2-4.19.2-release.jar       | None                                     |

	Loaded coremods (and transformers): 
ToolProgressionPlugin (toolprogression-core-1.12.2-1.6.6.jar)
  tyra314.toolprogression.core.asm.ToolProgressionClassTransformer
LibrarianLib Plugin (librarianlib-1.12.2-4.19.2-release.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
Quark Plugin (Quark-r1.6-177.jar)
  vazkii.quark.base.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
F5FixLoadingPlugin (f5fix-1.2.jar)
  de.morrien.f5fix.F5FixTransformer
CharmLoadingPlugin (Charm-1.12.2-1.3.6.jar)
  svenhjol.charm.base.CharmClassTransformer
No More Glowing Pots (nomoreglowingpots-1.2.jar)
  zabi.minecraft.nomoreglowingpots.PotionTransformer
LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 436.02' Renderer: 'GeForce GTX 980 Ti/PCIe/SSE2'
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 16
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 436.02
	OpenGlRenderer: GeForce GTX 980 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by BlackJar72** [comment]
Did you change basalt or volcanic ash to a different block in the config?

Try this and see if it helps.
http://www.mediafire.com/file/iiwav2r0m1nbcnu/ClimaticBiomes-2.14.6b-MC1.12.2.jar/file

**Comment by ghost** [comment]
Do you have a copy of your mod loadout before upgrading to v2.14.6?

**Comment by BlackJar72** [comment]
Try 2.14.7 and see if that helps.

**Comment by Thombias** [comment]
> Did you change basalt or volcanic ash to a different block in the config?
> 
> Try this and see if it helps.
> http://www.mediafire.com/file/iiwav2r0m1nbcnu/ClimaticBiomes-2.14.6b-MC1.12.2.jar/file

I didn't change the ash/basalt blocks in the configs and my mod loadout is almost unchanged. (I only removed statskeeper because i realised i don't need it.)
But i think i found the problem. It has nothing to with the mod blocks, it's the volcanoes.
Leaving everything at default doesn't crash anymore but as soon as i set volcanoes to false it crashes. 
VolcanicIslands set to false doesn't crash but Volcanoes set to false does. (The config option at the very top) I think that's because it is linked to MountainVariants and something isn't quite working how it should in mod versions past 2.14.5. I could be wrong about that though.
Tested on v2.14.7

**Comment by BlackJar72** [comment]
OIC, that actually was a mistake; turning off the volcanoes stopped the blocks from existing (I forgot that), but the new option configured the volcano biome whether it existed or not.  Ooop!  Well, now the existence of the blocks can be configured separately and they have vanilla stand-in if you set them not to exist (black stained clay for basalt and gravel for ash).

Try version 2.14.8, it should work.

**Comment by Thombias** [comment]
Will try it, thank you for keeping on updating and improving this mod. :)

Edit: Works like a charm now! Again thank you so much!
