### ISSUE TITLE
Worldgen crash when teleporting through a Rift from Arcane World

### ISSUE THREAD

**Issue by Not-February** [BlackJar72/ClimaticBiomePlacement#48]
Alright, so I've been getting an odd crash on my dedicated server through a little-documented feature from [Arcane World](https://www.curseforge.com/minecraft/mc-mods/arcane-world) while using the Climatic world type - it doesn't always seem to happen, since two other players have gone through different rifts without causing the server to crash.

Rifts are fairly rare things that spawn in the sky with worldgen, and when an entity goes through them(usually has to be a player), they are teleported to a "paired" rift elsewhere in the world _very_ far away from the first one - even if that part of the world hasn't been generated quite yet. That's my understanding of it mechanically, anyways - go through black hole in the sky, end up somewhere else with a hole in the sky that you can go back through to end up where you started.

The reason I'm bringing this up here is because the [crash log](https://gist.github.com/Febilian/91fd3f53df2e67cb891eaf2bdc0855e4) specifically mentioned this mod.

I am guessing it has something to do with the _staggering_ distance a rift attempts to teleport you all at once and weird interactions with how Climatic Biomes tries to figure out where to put things.

When the server starts up again, it's fine unless someone enters the rift in question again - then the crash happens again. I thought I should let you know about it, though.

I'm not sure if this is specifically an issue with Climatic Biomes or Arcane World, so if it isn't this mod I can go post this on the other's issue tracker.

**Comment by BlackJar72** [comment]
Try version 2.14.15.
