### ISSUE TITLE
[Suggestion] Extreme Hills Edge biome

### ISSUE THREAD

**Issue by QuantumStatement** [BlackJar72/ClimaticBiomePlacement#5]
[Extreme Hills Edge](https://minecraft.gamepedia.com/Mountains#Mountain_Edge) (or Mountains Edge in 1.13+) is vanilla biome that not used in world generation since 1.7.2 but still accessible through Customized/Buffet world type
![img](https://d1u5p3l4wpay3k.cloudfront.net/minecraft_gamepedia/a/ac/Extreme_Hills_Edge_Buffet.png)
It would be great if this biome was used in your mod

**Comment by BlackJar72** [comment]
It's an idea.  I've actually been thinking about doing more with mountains in general, and it wouldn't be the first old biome I've brought back.

**Comment by BlackJar72** [comment]
I really just see a place for them, where this would fit into this system.  You know, you can actually add this yourself through the custom config.
