### ISSUE TITLE
[Suggestion] adding a config option to change the BurnTime value of the Peat Block

### ISSUE THREAD

**Issue by gatoborrachon** [BlackJar72/ClimaticBiomePlacement#51]
i wanted to change the fuel value of this block, i know i can just download the mod and change it myself, but in case you will add another update, i think this option would be nice to implement

**Comment by BlackJar72** [comment]
OK.  That should not be hard.  I've been thinking of experimenting with some features and making a new version, so I'll probably just include it in that unless I just decide not to make the bigger update soon.

**Comment by BlackJar72** [comment]
Done!
