### ISSUE TITLE
[Crash] Issue when generating a new world

### ISSUE THREAD

**Issue by gatoborrachon** [BlackJar72/ClimaticBiomePlacement#52]
Whenever i start a new world the game freezes, i checked the crash report folder and i got this:
https://pastebin.com/JyacNNHM

i have like 240 mods, maybe i should do a binary search but i remember that the previous version had not issues (i think it should be 2.15.8)

EDIT: I can confirm that 2.15.8 does not have this issue

Versions:
ClimaticBiomes-2.16.1
Forge-14.23.5.2854

**Comment by BlackJar72** [comment]
I have determined that I've broken something in the Just Enough IDs support ... I'm not sure what or how, but that seems to be the problem, it only crashes when using and alternate classes that are only used with JEID.

**Comment by gatoborrachon** [comment]
many thanks, i just saw the changelog of 2.16.2, let me try it to confirm
