### ISSUE TITLE
Dynamic Trees Compatability

### ISSUE THREAD

**Issue by Scrayyg** [BlackJar72/ClimaticBiomePlacement#7]
Minecraft: 1.12.2
Forge: 14.23.5.2796
ClimaticBiomes-2.3.3-MC1.12.2-sources
ClimaticBiomes-DynamicTreesCompat-1.0.1-MC1.12.2
DynamicTrees-1.12.2-0.9.1f

Issue:
Minecraft fails to start as Dynamic Trees Compat calls for climaticbiomesjbg any as a dependency. Tested with just these 3 mods installed, I couldn't find a download for anything called climaticbiomesjbg so I assumed that it was an error.

**Comment by BlackJar72** [comment]
The problem is I uploaded the wrong file by mistake -- ClimaticBiomes-2.3.3-MC1.12.2-sources isn't actually the mod, just the source code.  Use the new file I just uploaded and it should work (ClimaticBiomes-2.3.3-MC1.12.2.jar = climaticbiomesjbg).  Sorry about the mixup.
