### ISSUE TITLE
Crash during world creation

### ISSUE THREAD

**Issue by Mongole** [BlackJar72/ClimaticBiomePlacement#8]
So i get this crash when I try creating a world using the climatic world gen, the crash is pointed at Exception generating new chunk
Using Forge 2780
Crash Report below
https://paste.ee/p/Hxxxf

**Comment by BlackJar72** [comment]
There seems to be a conflict with another mod -- but with so many I can't be sure which one.  My best guess is that somewhere is a core mod that changes the chunk provider.  I do not support modded chunk providers.

It might be possible, if you added biomes in the configs that you made a mistake, though if so it should have protected itself by treating it as plain.  Either way, I don't think I can do anything about it.

**Comment by BlackJar72** [comment]
I may have just fixed this.  I forgot to register something, and so it tries to generate terrain without any actual biomes when a frozen river should be placed.

**Comment by Mongole** [comment]
That is a good find, maybe it correlates with the reason i found out was causing the crashing on my part, seems like climatic biomes conflicts in some way with the traverse configs, it seems if you disable 2 or more biomes in the traverse config then generating a climatic world will always crash but it doesn't crash if you only disable one biome in the traverse config, i tend to disable any snowy biome.
heres the crash log with only climatic biomes and traverse loaded with 2 biomes disabled
https://paste.ee/p/szbny

**Comment by BlackJar72** [comment]
That's strange -- when you remove Traverse biomes, do you remove the biomes from the Traverse compatibility files? When it starts up it tries to populate its biome id list with those biomes, and will crash if it doesn't find them.

**Comment by Mongole** [comment]
i just go into the traverse folder inside confg and from the traverse.cfg set the disable"BiomeName"=false into true which force disables them but it doesn't cause any problems using the default or BoP world gen

**Comment by BlackJar72** [comment]
Have you looked at ClimaticBiomes/BiomeConfig/Traverse yet?  You need to remove biomes that you disable in Traverse from those lists too.

**Comment by Mongole** [comment]
Hadn't thought of checking the cliomaticbiomes folder, when removing entries from the subfiles in the traverse folder the game crash https://paste.ee/p/34mMQ, but then again im not sure how to go about removing them if its not by simply deleting the temp (texthere) lines (or removing the traverse:biome ,)
but one odd thing i came across is if i have the biomes disabled in the traverse.cfg and delete the climaticbiomes traverse folder so it can re-generate then the crash doesn't happen if its only those two mod loaded but loading in more mods causes the same crash as my second post

**Comment by BlackJar72** [comment]
You just need to delete any line that has a biome you removed in it.

There are more advanced things you can do, and a readme file with instructions, but if you are not sure just delete the line.  If you edit the lines they must still have the same format and a valid biome where ever a biome is now.
